name: wf-cd-develop
on:
  push:
    branches:
      - develop
jobs:
  upload-job-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: Build Artifacts with Parcel
        run: npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"
      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
          name: build-artifact-develop
  deploy-job-develop:
    needs: upload-job-develop
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: develop-env
    steps:
      - name: Deploy Build Artifacts on Git Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: build-artifact-develop
          token: ${{secrets.GITHUB_TOKEN}}